export const data = [
    {
        id: 0,
        imgUrl: "./logos/react.svg",
        label: "React.js",
        matched: false,
    },
    {
        id: 1,
        imgUrl: "./logos/angular.svg",
        label: "Angular",
        matched: false,
    },
    {
        id: 2,
        imgUrl: "./logos/astro.svg",
        label: "Astro",
        matched: false,
    },
    {
        id: 3,
        imgUrl: "./logos/ember.svg",
        label: "Ember.js",
        matched: false,
    },
    {
        id: 4,
        imgUrl: "./logos/vite.svg",
        label: "Vite",
        matched: false,
    },
    {
        id: 5,
        imgUrl: "./logos/vue.svg",
        label: "Vue.js",
        matched: false,
    },
    {
        id: 6,
        imgUrl: "./logos/laravel.svg",
        label: "Laravel",
        matched: false,
    },
    {
        id: 7,
        imgUrl: "./logos/nuxt.svg",
        label: "Nuxt.js",
        matched: false,
    },
    {
        id: 8,
        imgUrl: "./logos/playwright.svg",
        label: "Playwright",
        matched: false,
    },
    {
        id: 9,
        imgUrl: "./logos/preact.svg",
        label: "Preact",
        matched: false,
    },
    {
        id: 10,
        imgUrl: "./logos/solidity.svg",
        label: "Solidity",
        matched: false,
    },
    {
        id: 11,
        imgUrl: "./logos/remix.svg",
        label: "Remix",
        matched: false,
    },
    {
        id: 12,
        imgUrl: "./logos/storybook.svg",
        label: "Storybook",
        matched: false,
    },
    {
        id: 13,
        imgUrl: "./logos/svelte.svg",
        label: "Svelte",
        matched: false,
    },
    {
        id: 14,
        imgUrl: "./logos/vitest.svg",
        label: "Vitest",
        matched: false,
    },
];